SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
      ELSE 'PRODUTO BARATO'
      END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS;

SELECT NOME, LIMITE_DE_CREDITO,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE'
      WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
      ELSE 'CLIENTE PEQUENO'
      END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES ORDER BY CLASSIFICACAO, LIMITE_DE_CREDITO DESC