SELECT * FROM TABELA_DE_CLIENTES

SELECT CIDADE,IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE,IDADE;

SELECT DISTINCT CIDADE,AVG(IDADE) FROM TABELA_DE_CLIENTES GROUP BY CIDADE ORDER BY CIDADE

SELECT EMBALAGEM, COUNT(*) AS "NUMERO DE PRODUTOS" FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM ORDER BY EMBALAGEM

SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;

SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035'

SELECT * FROM ITENS_NOTAS_FISCAIS

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) FROM ITENS_NOTAS_FISCAIS GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 ORDER BY SUM(QUANTIDADE) DESC

SELECT * FROM TABELA_DE_CLIENTES

SELECT NF.CODIGO_DO_PRODUTO, TB.NOME_DO_PRODUTO, SUM(NF.QUANTIDADE) 
FROM ITENS_NOTAS_FISCAIS NF INNER JOIN TABELA_DE_PRODUTOS TB
ON TB.CODIGO_DO_PRODUTO = NF.CODIGO_DO_PRODUTO
GROUP BY NF.CODIGO_DO_PRODUTO, TB.NOME_DO_PRODUTO HAVING SUM(NF.QUANTIDADE) > 394000 ORDER BY SUM(NF.QUANTIDADE) DESC

INSERT INTO TABELA_DE_CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, 
SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) 
VALUES ('23412632331', 'Juliana Silva', 'R. Tramandai', '', 'Bangu', 'Rio de Janeiro', 
'RJ', '23400000', TO_DATE('1989-02-04','YYYY-MM-DD'), 28, 'F', 180000.0000, 24500, 0);


SELECT DISTINCT
TC.CPF AS CPF_TC
,TC.NOME
FROM
TABELA_DE_CLIENTES TC
LEFT JOIN
NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF
WHERE NF.CPF IS NULL;


