CREATE OR REPLACE PROCEDURE APP_INCLUIR_CLIENTE
    (p_ID IN CLIENTE.ID%type,
    p_RAZAO IN CLIENTE.RAZAO_SOCIAL%type,
    p_CNPJ IN CLIENTE.CNPJ%type,
    p_SEG_MERCADO IN CLIENTE.SEGMERCADO_ID%type,
    p_FATURAMENTO IN CLIENTE.FATURAMENTO_PREVISTO%type
    )
IS
BEGIN
    INCLUIR_CLIENTE(p_ID,p_RAZAO,p_CNPJ,p_SEG_MERCADO,p_FATURAMENTO);
END;

EXECUTE APP_INCLUIR_CLIENTE(6,'SEGUNDO CLIENTE INCLUIR POR USER_APP', '77777',2,100000);

SELECT * FROM CLIENTE ORDER BY ID;