CREATE TABLE TAB_FETCH
(ID INTEGER, NOME VARCHAR(10), VALOR VARCHAR(10));
INSERT INTO TAB_FETCH VALUES (1,'PRODUTO1',10);
INSERT INTO TAB_FETCH VALUES (2,'PRODUTO2',10);
INSERT INTO TAB_FETCH VALUES (3,'PRODUTO3',10);
INSERT INTO TAB_FETCH VALUES (4,'PRODUTO4',10);
INSERT INTO TAB_FETCH VALUES (5,'PRODUTO5',10);
INSERT INTO TAB_FETCH VALUES (6,'PRODUTO6',10);
INSERT INTO TAB_FETCH VALUES (7,'PRODUTO7',10);
INSERT INTO TAB_FETCH VALUES (8,'PRODUTO8',10);
INSERT INTO TAB_FETCH VALUES (9,'PRODUTO9',10);

SET SERVEROUTPUT ON;
DECLARE
    v_NOME VARCHAR2(10);
    v_VALOR FLOAT;
    v_VALOR_ACUMULATIVO FLOAT := 0;
    CURSOR CURSOR1 IS SELECT NOME, VALOR FROM TAB_FETCH WHERE MOD(ID,2) = 0;
BEGIN
    OPEN CURSOR1;    
    FETCH CURSOR1 INTO v_NOME, v_VALOR;
    WHILE v_VALOR_ACUMULATIVO <= 30 LOOP
        v_VALOR_ACUMULATIVO := v_VALOR_ACUMULATIVO + v_VALOR;
        FETCH CURSOR1 INTO v_NOME, v_VALOR;
    END LOOP;  
    CLOSE CURSOR1;
    dbms_output.put_line('VALOR DO PRODUTO = ' || v_NOME);
END;