SELECT * FROM CLIENTE ORDER BY ID;
SET SERVEROUTPUT ON
EXECUTE INCLUIR_CLIENTE(9,'ACADEMIA 1234', '12332145698715', 2, 30000);
EXECUTE INCLUIR_CLIENTE(20,'EVONETWORK', '77777777777777', 3, 70000);
SET SERVEROUTPUT ON

create or replace PROCEDURE incluir_cliente
(
p_ID CLIENTE.ID%type,
p_RAZAO CLIENTE.RAZAO_SOCIAL%type,
p_CNPJ CLIENTE.CNPJ%type,
p_SEGMERCADO CLIENTE.SEGMERCADO_ID%type,
p_FATURAMENTO CLIENTE.FATURAMENTO_PREVISTO%type
)
IS
v_CATEGORIA CLIENTE.CATEGORIA%type;
v_CNPJ CLIENTE.CNPJ%type;
BEGIN
   v_CATEGORIA := categoria_cliente(p_FATURAMENTO);
    formata_cnpj(p_CNPJ,v_CNPJ);
   INSERT INTO CLIENTE
   VALUES 
   (p_ID, p_RAZAO, v_CNPJ, p_SEGMERCADO, SYSDATE, p_FATURAMENTO, v_CATEGORIA);
   COMMIT;
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        raise_application_error(-20010,'CLIENTE JÁ CADASTRADO !!!');
END;